function configs = Hyd_IK_2(in1,in2)
%Hyd_IK_2
%    CONFIGS = Hyd_IK_2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2023-12-24 11:38:43

Pe1 = in2(1,:);
Pe2 = in2(2,:);
Pe3 = in2(3,:);
alpha = in1(:,1);
beta = in1(:,2);
t2 = cos(alpha);
t3 = cos(beta);
t4 = sin(alpha);
t5 = sin(beta);
t6 = Pe2.^2;
t7 = Pe3.^2;
t8 = t4.^2;
t9 = t2.*(1.3e+1./1.25e+2);
t10 = t3.*(1.3e+1./1.25e+2);
t11 = t5.*(1.3e+1./1.25e+2);
t14 = t5.*1.04e-1i;
t16 = t4.*t5.*(-1.3e+1./1.25e+2);
t17 = t2.*t3.*1.368e-1;
t19 = t2.*t3.*1.368e-1i;
t12 = -t10;
t13 = t4.*t11;
t15 = t4.*t10;
t18 = -t17;
t20 = -t19;
t21 = t9-1.3e+1./1.25e+2;
t22 = t8.*1.871424e-2;
t23 = -t22;
t24 = t21.^2;
t26 = t12+t13+1.3e+1./1.25e+2;
t27 = t10+t13-1.3e+1./1.25e+2;
t25 = t6+t7+t23;
t28 = abs(t26);
t29 = abs(t27);
t30 = sqrt(t25);
t31 = t28.^2;
t32 = t29.^2;
t33 = -t30;
t34 = t30.*1i;
t35 = t11+t18+t30-2.16e-2;
t39 = t15+t18+t30-2.16e-2;
t36 = t11+t17+t33+2.16e-2;
t37 = abs(t35);
t40 = abs(t39);
t38 = abs(t36);
t41 = t37.^2;
t43 = t40.^2;
t42 = t38.^2;
mt1 = [atan2(Pe3.*t4.*(-1.368e-1)-Pe2.*t30,Pe2.*t4.*(-1.368e-1)+Pe3.*conj(t30)),Pe1+t13-t2.*t5.*1.368e-1,angle(t10-t14+t16+t20+t34+-1.04e-1-2.16e-2i)-acos(1.0./sqrt(t31+t42).*(t31+t42-1.903615999999999e-2).*(1.25e+2./5.2e+1))];
mt2 = [angle(t12+t14+t16+t20+t34+1.04e-1-2.16e-2i)+acos(1.0./sqrt(t32+t41).*(t32+t41-1.903615999999999e-2).*(1.25e+2./5.2e+1)),angle(t9+t20+t34+t3.*t4.*1.04e-1i+-1.04e-1-2.16e-2i)-acos(1.0./sqrt(t24+t43).*(t24+t43-1.903615999999999e-2).*(1.25e+2./5.2e+1))];
configs = [mt1,mt2];
end
